### ISSUE TITLE
Update arm version

### ISSUE THREAD

**Issue by mohe2015** [radare/radare2-bin#1]
Can you update the arm version, please? Or is there some automated build server where I can download the latest version by myself?

**Comment by radare** [comment]
You can build it with sys/android.sh arm

But i’ll publish the new binaries next week

Sorry for the delay. Busy days :)

**Comment by radare** [comment]
try again

**Comment by mohe2015** [comment]
I'm using it on the pc now but on the phone it tells me: error: only position independent executables (PIE) are supported

**Comment by radare** [comment]
It should be building with -pie and -fPIC 

Try with setting this in cflags and ldflags

Maybe one of the android shellscripts got broken :?
